---
abstract: 'turn "1984" into "nineteen eighty-four", etc'
author:
  - 'Sean Burke <sburke@bowers.com>'
build_requires:
  Test: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-EN-Numbers-Years
requires:
  Exporter: '0'
  Lingua::EN::Numbers: '1.01'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Lingua-EN-Numbers-Years
  repository: https://github.com/neilbowers/Lingua-EN-Numbers-Years.git
version: 1.01_01
