# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lingua-EN-Numbers-Years
version:      1.01
version_from: lib/Lingua/EN/Numbers/Years.pm
installdirs:  site
requires:
    Lingua::EN::Numbers:           1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
